app:
    resource: "@AppBundle/Controller/"
    type:     annotation
root:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }
user_create:
    path: /user/create
    defaults: { _controller: AppBundle:User:create }
user_login:
    path: /user/login
    defaults: { _controller: AppBundle:User:login }
user_get:
    path: /user/{id}
    defaults: { _controller: AppBundle:User:get }
card_create:
    path: /card/create
    defaults: { _controller: AppBundle:Card:create }
card_get:
    path: /card/{id}
    defaults: { _controller: AppBundle:Card:getCard }
deck_get:
    path: /deck/{id}
    defaults: { _controller: AppBundle:Card:getDeck }
card_share:
    path: /card/{id}/user/{userId}
    defaults: { _controller: AppBundle:Card:share }
category_list:
    path: /category/list
    defaults: { _controller: AppBundle:Category:list }